// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/icon-variants/FacetedPurplePiece.tsx": () => import("../components/mockups/icon-variants/FacetedPurplePiece.tsx"),
  "./components/mockups/icon-variants/JigsawPiece.tsx": () => import("../components/mockups/icon-variants/JigsawPiece.tsx"),
  "./components/mockups/icon-variants/LargeMeasurePiece.tsx": () => import("../components/mockups/icon-variants/LargeMeasurePiece.tsx"),
  "./components/mockups/icon-variants/LargePurplePiece.tsx": () => import("../components/mockups/icon-variants/LargePurplePiece.tsx"),
  "./components/mockups/icon-variants/LargeRtoPiece.tsx": () => import("../components/mockups/icon-variants/LargeRtoPiece.tsx"),
  "./components/mockups/icon-variants/LetterformPuzzle.tsx": () => import("../components/mockups/icon-variants/LetterformPuzzle.tsx"),
  "./components/mockups/icon-variants/OrbitMark.tsx": () => import("../components/mockups/icon-variants/OrbitMark.tsx"),
  "./components/mockups/icon-variants/SculptedPurplePiece.tsx": () => import("../components/mockups/icon-variants/SculptedPurplePiece.tsx"),
  "./components/mockups/icon-variants/VioletStampPiece.tsx": () => import("../components/mockups/icon-variants/VioletStampPiece.tsx")
};
